#!/bin/bash

title="Power Menu"
location=1
width=15
xoffset=40
yoffset=70

typeset -A menu
menu=(
    [  - X session]="i3-msg exit"
    [  - Sleep]="systemctl suspend"
    [  - Lock]="~/Documents/Projets/scripts/lock.sh"
    [  - Power off]="systemctl poweroff"
    [  - Reboot]="systemctl reboot"
)

typeset -A colors
colors=(
    [color-flag]="#EEEEEE"
)

